[storage]
storage-node ansible_host=192.168.56.50

[idp]
idp-node ansible_host=192.168.56.20

[lb]
lb-node ansible_host=192.168.56.10 ansible_port=2222

[bastions]
bastion-01 ansible_host=192.168.56.11
bastion-02 ansible_host=192.168.56.12

[target]
test-server ansible_host=192.168.56.60

[all:vars]
ansible_user=vagrant
ansible_password=vagrant
