---
- name: restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: restart journal-upload
  ansible.builtin.systemd:
    name: systemd-journal-upload.service
    state: restarted
