---
- name: daemon reload
  systemd:
    daemon_reload: true

- name: restart keycloak
  systemd:
    name: keycloak
    state: restarted

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
