---
- name: daemon reload idp
  become: true
  become_user: secos
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ secos_uid }}"
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: restart idp
  become: true
  become_user: secos
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ secos_uid }}"
  ansible.builtin.systemd:
    name: secos-idp
    state: restarted
    scope: user

- name: reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
