---
- name: daemon reload
  systemd:
    daemon_reload: true

- name: restart grafana-forward
  systemd:
    name: grafana-forward
    state: restarted

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
