---
- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart grafana-forward
  ansible.builtin.systemd:
    name: grafana-forward
    state: restarted

- name: reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
