---
- name: daemon reload agents
  become: true
  become_user: secos
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ secos_uid }}"
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: restart agents
  become: true
  become_user: secos
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ secos_uid }}"
  ansible.builtin.systemd:
    name: secos-agents
    state: restarted
    scope: user
